version: 2

project_name: hg

before:
  hooks:
    - go mod tidy

builds:
  - id: hg
    main: ./cmd/hg
    binary: hg
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: unix-tarballs
    builds: [hg]
    format: tar.gz
    wrap_in_directory: false
    files:
      - LICENSE*
      - README.md
    name_template: "hg_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: windows-zips
    builds: [hg]
    format: zip
    wrap_in_directory: false
    files:
      - LICENSE*
      - README.md
    name_template: "hg_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^ci:"
      - "^docs:"
      - "^test:"

release:
  draft: false
  prerelease: false

brews:
  - name: hg
    ids: [unix-tarballs]
    skip_upload: true
    repository:
      owner: TODO
      name: TODO
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: watchthelight-bot
      email: admin@watchthelight.org
    description: "Hypergraph & HoTT tooling in Go"
    homepage: "https://github.com/watchthelight/HypergraphGo"
    license: "MIT"
    install: |
      bin.install "hg"

scoops:
  - name: hg
    ids: [windows-zips]
    skip_upload: true
    repository:
      owner: TODO
      name: TODO
      token: "{{ .Env.SCOOP_GITHUB_TOKEN }}"
    commit_author:
      name: watchthelight-bot
      email: admin@watchthelight.org
    description: "Hypergraph & HoTT tooling in Go"
    homepage: "https://github.com/watchthelight/HypergraphGo"
    license: "MIT"
