version: 2
project_name: hottgo

builds:
  - id: cli
    main: ./cmd/hottgo
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    binary: hottgo
    ldflags:
      - -s -w
      - -X github.com/watchthelight/HypergraphGo/internal/version.Version={{.Version}}
      - -X github.com/watchthelight/HypergraphGo/internal/version.Commit={{.Commit}}
      - -X github.com/watchthelight/HypergraphGo/internal/version.Date={{.Date}}

archives:
  - id: tgz
    builds: [cli]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
