version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: hottgo
    main: ./cmd/hg
    binary: hottgo
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

checksum:
  name_template: "checksums.txt"

sboms:
  - artifacts: [binary]
    generator: cyclonedx

archives:
  - id: tgz_zip
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  draft: false
  prerelease: false
  mode: replace

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^ci'
      - '^test'

# Homebrew/Scoop taps can be added later; kept commented for future:
# brews:
#   - tap:
#       owner: watchthelight
#       name: homebrew-tap
#     name: hottgo
#     commit_author:
#       name: goreleaser
#       email: noreply@github.com
# scoops:
#   - bucket:
#       owner: watchthelight
#       name: scoop-bucket
#     name: hottgo
