brews:
  - name: hottgo
    ids: [tgz_zip]
    repository:
      owner: watchthelight
      name: homebrew-hottgo
    commit_author:
      name: watchthelight-bot
      email: admin@watchthelight.org
    homepage: https://github.com/watchthelight/HypergraphGo
    description: Hypergraph & HoTT tooling in Go
    license: MIT
    skip_upload: false

scoops:
  - name: hottgo
    ids: [tgz_zip]
    repository:
      owner: watchthelight
      name: scoop-bucket
    commit_author:
      name: watchthelight-bot
      email: admin@watchthelight.org
    homepage: https://github.com/watchthelight/HypergraphGo
    description: Hypergraph & HoTT tooling in Go
    license: MIT
    skip_upload: false
