name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Verify modules
        run: |
          go mod tidy
          go mod verify

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./... -count=1 -v
