name: CI
on:
  push:
  pull_request:

jobs:
  test:
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    # Force bash as the shell on all runners (fixes Windows 'exit' and POSIX checks).
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: false   # root fix: do not require go.sum to restore cache

      - name: Show module state
        run: |
          echo "PWD=$(pwd)"
          echo "GOMOD=$(go env GOMOD)"
          ls -la

      - name: Tidy, download, verify modules
        run: |
          go mod tidy
          # If there are external deps this will generate go.sum; if not, that's fine.
          go mod download all || true
          go mod verify

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -count=1 -v
